---- Base app schema


-- User
CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username   varchar(128) NOT NULL UNIQUE,
    -- AUTH
    pwd        varchar(256),
    pwd_salt   uuid         NOT NULL DEFAULT gen_random_uuid(),
    token_salt uuid         NOT NULL DEFAULT gen_random_uuid()

);

CREATE TABLE "task"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title varchar(128) NOT NULL UNIQUE,
    done  bool         NOT NULL DEFAULT false
);

create sequence api_key_id_seq as integer;
create sequence application_id_seq as integer;
create sequence public.application_registry_id_seq as integer;
create sequence public.merchant_channel_id_seq as integer;
create sequence sequencers_id_seq as integer;

create table "api_key"
(
    id          integer primary key    not null default nextval('api_key_id_seq'::regclass),
    created_at  timestamp(3) without time zone not null default CURRENT_TIMESTAMP,
    updated_at  timestamp(3) without time zone not null,
    key_name    character varying(100) not null,
    key_content character varying(500) not null,
    enabled     boolean                not null default true
);

create table application
(
    id         integer primary key    not null default nextval('application_id_seq'::regclass),
    created_at timestamp(3) without time zone not null default CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone not null,
    app_id     character varying(50)  not null,
    app_name   character varying(50)  not null,
    topic      character varying(100) not null,
    enabled    boolean                not null default true
);


create table "merchant_channel"
(
    id         integer primary key    not null default nextval('merchant_channel_id_seq'::regclass),
    created_at timestamp(3) without time zone not null default CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone not null,
    ref_id     character varying(50)  not null,
    name       character varying(100) not null,
    ref_type   character varying(100) not null,
    token      character varying(500) not null
);
create unique index merchant_channel_ref_id_ref_type_key on merchant_channel using btree (ref_id, ref_type);


create table "application_registry"
(
    id         integer primary key not null default nextval('application_registry_id_seq'::regclass),
    created_at timestamp(3) without time zone not null default CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone not null,
    enabled    boolean             not null default true,
    channel_id integer,
    app_id     integer,
    foreign key (app_id) references application (id)
        match simple on update cascade on delete cascade,
    foreign key (channel_id) references merchant_channel (id)
        match simple on update cascade on delete cascade
);
create unique index application_registry_channel_id_app_id_key on application_registry using btree (channel_id, app_id);


create table "sequencers"
(
    id         integer primary key   not null default nextval('sequencers_id_seq'::regclass),
    created_at timestamp(3) without time zone not null default CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone not null,
    name       character varying(50) not null,
    data       integer               not null default 0
);
create unique index "sequencers_name_key" on sequencers using btree (name);

-- alter sequence api_key_id_seq owner to femto;
alter sequence api_key_id_seq owned by api_key.id;
-- alter sequence application_id_seq owner to femto;
alter sequence application_id_seq owned by application.id;
-- alter sequence public.application_registry_id_seq owner to femto;
alter sequence application_registry_id_seq owned by application_registry.id;
-- alter sequence public.merchant_channel_id_seq owner to femto;
alter sequence merchant_channel_id_seq owned by merchant_channel.id;
-- alter sequence sequencers_id_seq owner to femto;
alter sequence sequencers_id_seq owned by sequencers.id;





